version: "3.9"
services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'secret-pw'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
      - './initial.sql:/docker-entrypoint-initdb.d/initial.sql'
